import tkinter as tk
def hi():
    name=entry.get()
    print('hi', name)
root = tk.Tk()

textLabel = tk.Label(root, text = "put your A day classes here: ")
textLabel.pack()
root.title("scheduler for classes")
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
button=tk.Button(root, text = 'next ', command=hi)
button.pack()



textLabel = tk.Label(root, text = "put your B day classes here: ")
textLabel.pack()
root.title("scheduler for classes")
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
entry=tk.Entry(root)
entry.pack()
button=tk.Button(root, text = 'next', command=hi)
button.pack()



root.mainloop()
